'''
SENA CBA CENTRO DE BIOTECNOLOGIA AGROPECUARIA
PROGRAMACION DE SOFTWARE

FICHA: 2877795
AUTOR: NICOLAS ANDRES ACOSTA HIGUERA
PROYECTO: HOLA_MUNDO DJANGO (holass/test.py)
FECHA: 02-09-2024
VERSION: 3.0
'''

# Importaciones externas de Django.
from django.test import TestCase

# Create your tests here.
