# Generated by Django 5.1 on 2024-09-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    clase que define la migración de la aplicación.
    
    Args:
        migrations: Clase que define una migración de Django.
        
    Returns:
        str: La migración de la aplicación.
        
    """

    initial = True # Define la migración inicial en True igual a verdadero. 

    dependencies = [
    ] # Define las dependencias de la migración.

    operations = [
        migrations.CreateModel( # Crea el modelo.
            name='Post', # Nombre del modelo.
            fields=[ # Campos del modelo.
                ('id', models.BigAutoField(auto_created=True, # Campo id.
                                           primary_key=True, # Campo primary_key.
                                           serialize=False, # Campo serialize.
                                           verbose_name='ID' # Campo verbose_name.
                                           )
                 ),
                ('message', models.TextField()), # Campo message.
            ],
        ),
    ]
